package com.luv2code.springdemo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

//default bean id generated by Spring would be tennisCoach
@Component//("thatSillyCoach") Spring will automaticly register this bean, + bean id
public class TennisCoach implements Coach {
	
	private FortuneService fortuneService;
	
	// Spring will scan for a component that implements FortuneService interface
	// HappyFortuneService meets the requirement	
	@Autowired
	public TennisCoach(FortuneService theFortuneService) {
		fortuneService = theFortuneService;
	}

	@Override
	public String getDailyWorkout() {
		
		return "Practise your backhand volley";
	}

	@Override
	public String getDailyFortune() {
		return fortuneService.getFortune();
	}

}
